language: ruby
cache: bundler
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails test
  - bundle exec rake cucumber
notifications:
  email: false
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHJpZWNrZXJzJTNBc3R1Z2VuLmRlLyUyMXdKR1Zpek9xRHRZUWZRelJGciUzQXN0dWdlbi5kZQ"
    on_success: always
    on_failure: always
    on_start: never
