language: ruby
cache: bundler
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - echo $RIOT_WEBHOOK > foobar
  - cat foobar | tail -c +2
  - bundle exec rails test
  - bundle exec rake cucumber
notifications:
  email: false
  webhooks:
    urls:
      - $RIOT_WEBHOOK
    on_success: always
    on_failure: always
    on_start: never
