# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 462ba7b6cdeec4a4cab7389a3be88dccde4af87c2cc5aac4719934ce3b0f9a7764f17a627a4dee9d4701e387a9a2d55edb7b90a842211dd9a89e2adf03bd8afc

test:
  secret_key_base: 68e8b1f983e1656b25969fb901e5f3d5b74760967ea12844c46d23c053c277eec8c3cf1dbf8e62675050f063923346f770e747b680a12bb0205422e583e2fd98

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
